# Generated by Django 3.2.4 on 2022-01-20 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='cost',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='design',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='comp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
