# Generated by Django 3.2.4 on 2022-01-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220120_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_picture',
        ),
    ]
