# Generated by Django 3.2.4 on 2022-01-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
