# Generated by Django 3.2.4 on 2022-01-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
